# Generated by Django 2.2.14 on 2020-07-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_auto_20200703_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
